### ISSUE TITLE
No centering round rect correctly

### ISSUE THREAD

**Issue by emauro** [florent37/TutoShowcase#9]
I am trying to use TutoShowcase to show hint in a view that is a page of a ViewPager. For any view inside that view the roundrect is displayed displaced.  See the image.
![problem](https://cloud.githubusercontent.com/assets/4071116/18234537/b86563d0-72df-11e6-9e76-def0ece74ffe.png)

**Comment by sathya541** [comment]
Any solutions? I'm facing the same issue

**Comment by AlburIvan** [comment]
I'm currently dealing with this too, mind to share what TutoShowcase configuration you're using for that tutorial specifically?. I want to see if I can fix this and send a pull request

**Comment by AlburIvan** [comment]
@emauro I can't seem to reproduce it again at work to see if I can fix this. 

It is already fixed? or can someone supply the steps to reproduce this (maybe a simple example layout and code)

**Comment by florent37** [comment]
can you send me an example of layout ? It seems that the height of the status bar is not added correctly

**Comment by emauro** [comment]
@florent37 That's the problem. Layout is pretty simple. The problem is that the layout is for a view that is inside a ViewPager, which is inside a Fragment.

**Comment by darkholiday** [comment]
hey, did you figure it out yet ?

**Comment by AlburIvan** [comment]
As @florent37 said, the problem is with the height of the status bar...  
If I let the method `addRoundRectOnView` by default, the line with the statement  below will add the incorrect height.
 ` final int y = rect.top - getStatusBarHeight() - padding;`   
Will make my layout look like this:
![screenshot_16](https://cloud.githubusercontent.com/assets/10523232/19696666/2557ceb2-9ab6-11e6-85b8-c8333e6a02a8.png)

On the other hand if I remove the `getStatusBarHeight()` from the equation, it will correctly show the TutpShowCase view correctly **(for this case... at least)**  
![image](https://cloud.githubusercontent.com/assets/10523232/19696864/f4575a8e-9ab6-11e6-8b49-e94f60f09f62.png)

**Comment by darkholiday** [comment]
Thank you broh.
Keep it up

**Comment by hablema** [comment]
This is happening for me with circle when i add it to a fab. How can i correct it?

**Comment by 4ybaka** [comment]
Any solution? Still occurs.

**Comment by florent37** [comment]
play with ".setFitSystemWindow(true / false)"
